# Generated by Django 3.2.8 on 2022-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Direccion de correo electronico')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('content', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
    ]
